// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FbI7UW_-_qTEktl8cZAGFW65PWpuBus',
    appId: '1:472231421920:web:c9860cd0f6df3380ad2d85',
    messagingSenderId: '472231421920',
    projectId: 'notes-f3dc3',
    authDomain: 'notes-f3dc3.firebaseapp.com',
    storageBucket: 'notes-f3dc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO-RifDmDp6cQryBU6CwvqpdTECf_Y5bs',
    appId: '1:472231421920:android:5d81410cac79fc92ad2d85',
    messagingSenderId: '472231421920',
    projectId: 'notes-f3dc3',
    storageBucket: 'notes-f3dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMLDHfR9awf9CkMI7iS5ucIwNcKa2htY',
    appId: '1:472231421920:ios:0805ec03904535d7ad2d85',
    messagingSenderId: '472231421920',
    projectId: 'notes-f3dc3',
    storageBucket: 'notes-f3dc3.appspot.com',
    iosBundleId: 'com.lyrilab.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEMLDHfR9awf9CkMI7iS5ucIwNcKa2htY',
    appId: '1:472231421920:ios:b12464310bc9d14fad2d85',
    messagingSenderId: '472231421920',
    projectId: 'notes-f3dc3',
    storageBucket: 'notes-f3dc3.appspot.com',
    iosBundleId: 'com.lyrilab.notes.RunnerTests',
  );
}
